---
# file: roles/common/tasks/main.yml

- name: Install the package wget
  apt:
    name: wget
    state: present

# create /opt/ directory if it doesn't exist
- file:
    path: /opt
    state: directory
    mode: 0755

...